### ISSUE TITLE
Don't work on Next.js with the error "Error [ERR_REQUIRE_ESM]: Must use import to load ES Module..."

### ISSUE THREAD

**Issue by prettydev** [mmomtchev/rlayers#10]
```
Build error occurred
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /.../node_modules/ol/index.js
require() of ES modules is not supported.
require() of /.../node_modules/ol/index.js from /.../node_modules/rlayers/index.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename /.../node_modules/ol/index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /.../node_modules/ol/package.json.

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1015:13)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/workspace/totalscience/nextjs-blog/node_modules/rlayers/index.js:26:12)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14) {
  type: 'NodeError',
  code: 'ERR_REQUIRE_ESM'
}
```

**Comment by mmomtchev** [comment]
This is not a problem with rlayers - it is a problem between webpack and openlayers.

See https://github.com/openlayers/openlayers/issues/12525 for the detailed explanation and the solution

**Comment by ziyue5** [comment]
@mmomtchev Hi, I used the solution mentioned in the link and I even found https://github.com/openlayers/openlayers/issues/10470#issuecomment-782664014 . However, there is still an error:

./node_modules/rlayers/RFeature.js:70:11
Module not found: ESM packages (ol) need to be imported. Use 'import' to reference the package instead. 

Import trace for requested module:
./node_modules/rlayers/index.js
...

And the line 70 of RFeature.js is var ol_1 = require("ol");

Could I know if there are any other changes needed? Thank you so much!

**Comment by mmomtchev** [comment]
What bundler are you using and what is its configuration?

**Comment by ziyue5** [comment]
@mmomtchev Hi, I am using Next.js v12.1.0 and my next.config.js is:
```
const withTM = require("next-transpile-modules")([
  "rlayers",
  "ol",
  "lru-cache"
]);

module.exports = withTM();
```

**Comment by ziyue5** [comment]
@mmomtchev Thanks! But after I tried this solution, there is still an error:
```
Server Error
ReferenceError: document is not defined

This error happened while generating the page. Any console logs will be displayed in the terminal window.
Call Stack
new Zoom1
node_modules/ol/control/Zoom.js (56:21)
defaults
node_modules/ol/control.js (52:22)
new Map1
node_modules/ol/Map.js (79:46)
new RMap1
node_modules/rlayers/RMap.js (47:19)
...
```
Looks like it's a conflict with ol itself?

**Comment by ziyue5** [comment]
Yes, while I just searched, maybe I should try loading rlayers with dynamic import?

**Comment by mmomtchev** [comment]
rlayers does not have SSR, there used to be an experimental branch with SSR support but I am not working on it anymore. SSR for maps is very difficult - you don't have a layout engine when rendering server-side - which means you can't size your map windows and you cannot draw your map.

Just don't define `getServerSideProps` for pages containing maps.

**Comment by mmomtchev** [comment]
@ziyue5 Next has an optimization called *Automatic Static Optimization* - if it detects that your page does not contain any dynamic elements - it will automatically try to prerender it server-side. This will never work with `rlayers` which needs a layout engine. Check the documentation on how to disable it - one way is to have a custom `_app.js` with `getInitialProps`.

**Comment by chilli-andrew** [comment]
@mmomtchev in relations to your response above, this SO answer solved the issue for me.
https://stackoverflow.com/questions/53139884/next-js-disable-server-side-rendering-on-some-pages
