### ISSUE TITLE
Static Images

### ISSUE THREAD

**Issue by Jamiecharris** [mmomtchev/rlayers#104]
Sorry that I'm raising this as an issue, couldn't find the discussion feed. 

Just wondering if you have a similar example of this https://openlayers.org/en/latest/examples/static-image.html

Using your package? 

Also are you available for hire?

**Comment by mmomtchev** [comment]
Not for anyone involved in the criminal affair
Next time try to be less obvious

**Comment by Jamiecharris** [comment]
> Not for anyone involved in the criminal affair
> 
> Next time try to be less obvious

Sorry what, on your bio you mentioned your looking for work. Im building a visual inspection tool, and need an expert on openlayers. 

Again if you any examples using the above that would be much help.
