### ISSUE TITLE
Mouse icon offset from mouse in Storybook

### ISSUE THREAD

**Issue by scottboyd-ai** [mmomtchev/rlayers#113]
I am using rlayers alongside Storybook, and when I load the component in the storybook page, the mouse icon is offset from the actual mouse pointer location based on its distance from the top left corner of the map.

Two examples:
<img width="1485" alt="Screen Shot 2022-12-29 at 14 18 51" src="https://user-images.githubusercontent.com/10579185/210012547-ee3f1c9f-13b6-40e2-b76d-bca300a62feb.png">
<img width="1442" alt="Screen Shot 2022-12-29 at 14 17 26" src="https://user-images.githubusercontent.com/10579185/210012550-0a8e7179-2921-4f04-a734-366b4976f237.png">

I am using RInteractions.RDraw to draw on this map, and the drawing functionality is working as expected except that the drawing begins where the blue circle icon is, not where the mouse pointer is. This functionality is also working as expected in a normal create-react-app setting outside of Storybook.

This is my component:

```
const Map = () => {

  const mapRef = useRef({} as RMap)
  return (
    <RMap
      className='example-map'
      width="200vw"
      height="100vw"
      initial={{ center: fromLonLat([-105.084629, 40.4357083]), zoom: 20 }}
      ref={mapRef}
    >
      <RLayerTile
        properties={{ label: 'Google Maps' }}
        url='http://mt1.google.com/vt/lyrs=s&x={x}&y={y}&z={z}'
        attributions=''
      />
      <RLayerVector>
        {/* This is the style used for the drawn polygons */}
        <RStyle.RStyle>
          <RStyle.RStroke color='#0000ff' width={3} />
          <RStyle.RFill color='rgba(0, 0, 0, 0.75)' />
        </RStyle.RStyle>
        <RInteraction.RDraw

          type="Polygon"
          condition={altKeyOnly}
          freehandCondition={shiftKeyOnly}
        />
      </RLayerVector>
      <RLayerVector />
    </RMap>
  )
}
```

I understand if the scope of this issue is outside of the responsibility of the app, but I thought I'd at least bring it to the developer's attention.

**Comment by mmomtchev** [comment]
Storybook probably has some CSS transformation such as scale. There isn't much that can be done about it - try to keep the map canvas outside of this transformation.

**Comment by scottboyd-ai** [comment]
I wasn't able to solve this issue, but rendering the component in my app fixed the issue. I also noticed that there was no problem when the component was added to new project and put into storybook. The problem is probably some library or hardware issue that I'm not able to discover. Sorry for whoever finds this in the future looking for a solution, I don't have it.
