### ISSUE TITLE
onChange is never called

### ISSUE THREAD

**Issue by TrySpace** [mmomtchev/rlayers#117]
The docs say: "Called on every change", but it doesn't, unless the definition of 'change' is misunderstood, but it is not defined anywhere that change should constitute some specific change.

See: https://codesandbox.io/s/rlayers-onchange-tiudhx?file=/src/OpenlayersMap.jsx (new version, but older version behave the same)

I assume that things like changing zoomlevel would trigger `onChange`, but if not, which event would trigger it?, because any `RLayerVector` changing also does not trigger anything.

**Comment by mmomtchev** [comment]
No, `onChange` is actual changes of the map configuration. Use `onPointerMove` for an event that fires very rapidly on every movement, or `onMoveEnd` for one single event when the map stops moving.
