### ISSUE TITLE
high call rate `style` function on `RLayerVectorTile`, hits performance badly

### ISSUE THREAD

**Issue by vgrafe** [mmomtchev/rlayers#12]
Hi! 

I set up a `RLayerVectorTile` in my `RMap` that uses MVT format, and pull `pbf` files from my server. That layer has a lot of features... this leads the function passed to the `style` prop to be called thousands of times, over 10-20 seconds. This causes the render to freeze at times. 
Is there a way to manage the performance on client side to address this scenario? or should my team look into providing more tilesets with less features each?

Thanks!

**Comment by mmomtchev** [comment]
If your function returns a different style for every feature used, you have no way to improve the performance - whether you use *rlayers* or you use directly *OpenLayers*. In this case you have 2 choices: either reduce the number of features or use clustering.
If some features share the same styles - you can use the cache parameters - in this case *rlayers* wil call only your hashing function to check if a new style has to be computed and constructed.

**Comment by vgrafe** [comment]
You got it - the function returns 3 different styles depending on the feature type. One of those types makes for 99% of the features rendered... what cache parameters are you making mention of, Do you mean I should build a cache layer depending on the 'feature' and 'resolution' parameters sent to the function?

Unfortunately clustering does not seem to be an option for our use case (but I'll look into it more).

Thanks for such a fast response btw 🚀

**Comment by mmomtchev** [comment]
@vgrafe if one feature type represents 99% of the features, your best option, performance-wise, would be to move these features to a separate vector layer with a single fixed style

**Comment by vgrafe** [comment]
Makes sense. Thank you for the help!
