### ISSUE TITLE
Possible to have a button enable drawing a polygon on the map?

### ISSUE THREAD

**Issue by CrumpetsNTea** [mmomtchev/rlayers#120]
I'm working on adding a toolbar that has controls for enabling drawing a polygon on the map. I can't see an example of this in the RLayers examples though. I tried using a state variable (drawActive) that gets set to true when the user clicks the button, and then passing this as the condition for drawing being enabled. This results in a TS error.

Before I dive further into this, I want to make sure that what I'm trying to accomplish is possible with RLayers? Thanks!

**Comment by CrumpetsNTea** [comment]
Figured it out! Passing in the boolean as the draw condition works, but the TS error 
"Type 'boolean' is not assignable to type '(e: MapBrowserEvent<UIEvent>) => boolean'.ts(2322)" still persists.

**Comment by mmomtchev** [comment]
You can do it yourself or you can use an interaction, here is the example: https://mmomtchev.github.io/rlayers/#/draw

**Comment by CrumpetsNTea** [comment]
Passing the condition like so:
`
condition={() => {
              return drawActive;
            }}
`
resolves the TS error. However, passing the boolean directly as the condition also works. 
Having to return the boolean from this function is not ideal.

**Comment by mmomtchev** [comment]
The condition argument is the event, you have to use a closure if you want to pass an external variable.

**Comment by CrumpetsNTea** [comment]
Thanks @mmomtchev! It is in working order now, so will mark this as closed. Cheers
