### ISSUE TITLE
Property 'onDrawEnd' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<RDraw> & Readonly<RDrawProps>'

### ISSUE THREAD

**Issue by CrumpetsNTea** [mmomtchev/rlayers#123]
Getting TS error: Property 'onDrawEnd' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<RDraw> & Readonly<RDrawProps>' when trying to use the onDrawEnd prop on an RDraw component

```
        <RInteraction.RDraw
              onDrawEnd={(e: DrawEvent) => {
                // eslint-disable-next-line no-underscore-dangle
                return console.log(e.feature);
              }}
              type="Polygon"
              condition={shiftKeyOnly}
              freehandCondition={altShiftKeysOnly}
            />
```

The onDrawEnd function fires perfectly fine.

**Comment by mmomtchev** [comment]
It does seem to work for me, are you sure you have the latest version? Can you check what files are you including and whether you are using the CJS or the ES6 version - this depends on your bundler.

**Comment by CrumpetsNTea** [comment]
Yep, did not realize there was a newer version available. I have just upgraded to 1.4.8 and the issue is no longer present. We were running 1.4.5. Thank you for your time!
