### ISSUE TITLE
Is it possible to draw "hole" inside polygon with rlayers?

### ISSUE THREAD

**Issue by indapublic** [mmomtchev/rlayers#135]
Google telling that I can use `appendLinearRing` but I'm not sure how I can adopt it for rlayers.

**Comment by mmomtchev** [comment]
rlayers does not process the polygons in any way, everything that is supported by Openlayers is supported by rlayers. You can pass any geometry that follows its rules: https://openlayers.org/en/latest/apidoc/module-ol_geom_Polygon.html.

React is a declarative, and not a procedural framework. You are expected to construct the geometry before submitting it to the component. You can use `appendLinearRing` and then submit the resulting geometry.
