### ISSUE TITLE
Is it possible to have a layer attribution collapsed by default to his button form?

### ISSUE THREAD

**Issue by gillesserco** [mmomtchev/rlayers#136]
Hello

For some reason I have a small black in the attribution:

![attribution_black_box](https://user-images.githubusercontent.com/82219527/222093140-e79a1e5d-6225-4b78-8e05-d6d545eedf32.jpg)

I wonder if it is possible to have the attribution collapsed by default, to have it in his button form.

Thanks & best regards

Gilles

**Comment by mmomtchev** [comment]
No, it is mandatory as per OSM policy. Openlayers respects their decision and does not allow the collapsing of the attributions. Check your CSS, there is probably something missing.

**Comment by gillesserco** [comment]
Hello

Thanks for the info. Pb is I have no clue why I have this black square,... I already check around but found nothing.

gilles
