### ISSUE TITLE
RLayerWMTS refresh is dysfunctional

### ISSUE THREAD

**Issue by Irfy** [mmomtchev/rlayers#144]
See diff https://github.com/mmomtchev/rlayers/commit/9741ab50d7fa208eccb6527d7e90a4604903bf2c#diff-ad1e4aa7a9580e9395c34f4c0b39c7509c634287d3e0b2c04d3352da63c0753c

Two issues here.

1. `RLayerWMTS.refresh` causes unnecessary layer refresh.

Generally speaking, calling `this.createSource().then(() => super.refresh(prevProps));` without checking if anything actually changed causes the whole WMTS Layer to refresh every time an **unrelated** prop changes. This makes the map unusable, as the layer is re-initializing every time a prop changes, even though that prop has nothing to do with the WMTS layer. I currently have a `patch-package` snippet that removes any code from the refresh method and it works as expected, no map reload upon unrelated prop change.
> Solution: do not recreate the source unconditionally upon refresh. Do it **only** if `this.props.url` actually changed. (How we detect that here -- I do not know, so no PR)

2. The new code in the diff is problematic:
```
        this.createSource().then(() => {
            this.createSource(); <-- ignored Promise that changes this.source?!
            this.ol.setSource(this.source);
            this.attachOldEventHandlers(this.source);
        });
```
This means that, after the source is set by `this.createSource`, we trigger it again, but don't wait for its completion -- passing the current source to other places, but that source is **guaranteed** to get overwritten by the inner `createSource()` call. There seems to be no point in doing the inner call at all. I feel like the inner `createSource()` call is an unintended oversight.
> Solution: Remove the inner call.

**Comment by Irfy** [comment]
`REvent.tsx`:
```
    componentDidUpdate(prevProps: Readonly<P>, prev: Readonly<unknown>, snap: unknown): void {
        if (this.props !== prevProps) {
            debug('willRefresh', this, prevProps, this.props);
            this.refresh(prevProps);
        }
    }
```
Would a 1-level deep props comparison here help?

---

The code that exhibits the problematic WMTS refresh looks like this:

```
export default () => {
  const [pinCoords, setPinCoords] = React.useState(initialPinCoord);
...
  return (
...
          <RMap className="..." ...>
            <RLayerWMTS url="[fixed URL, never changes]" layer="..." />
            <RLayerVector>
              <RFeature feature={pinFeature}>...</RFeature>
            </RLayerVector>
            <RInteraction.RTranslate
              features={new Collection([pinFeature])} // same feature as in the preceding vector layer
              onTranslateEnd={React.useCallback((e: TranslateEvent) => {
                setPinCoords(e.coordinate); // this causes the unwanted full WMTS layer refresh
              }, [])}
            />
          </RMap>
```

**Comment by mmomtchev** [comment]
I agree, but this isn't related to this PR, from what I see, it has always been like this since the WMTS layer appeared. Very few people use it, so I am not surprised. I can't simply skip the refresh because this is the base class for all layers. I will add a smarter prop change detection.

**Comment by mmomtchev** [comment]
What properties change in your case? The `onSourceRedy` function? You can probably work around with `useCallback` until I release a fix.

Everything else besides the callback really warrants a rerfesh.

**Comment by Irfy** [comment]
> I agree, but this isn't related to this PR, from what I see, it has always been like this since the WMTS layer appeared. Very few people use it, so I am not surprised. I can't simply skip the refresh because this is the base class for all layers. I will add a smarter prop change detection.

The dysfunctional refresh is not related to the PR -- but that's just the first problem. The second problem where the source gets overwritten *after* it has been passed up is related to the PR -- the PR introduces a bug.

> What properties change in your case?

That's the thing -- nothing directly related to the WMTS layer changes. The change is on state variable that isn't even used anywhere. That is enough to trigger a full map reload. I'm pasting the fully reproducible minimal code below.

**Comment by Irfy** [comment]
```
import React from "react";
import { fromLonLat, toLonLat } from "ol/proj";
import { Point } from "ol/geom";
import { Feature } from "ol";
import { Coordinate } from "ol/coordinate";
import "ol/ol.css";

import pin from "./pin.svg";
import {
  RMap,
  ROSM,
  RInteraction,
  RLayerVector,
  RStyle,
  RFeature,
  RLayerWMTS,
} from "rlayers";

export const coords: Coordinate = [2.352, 48.861];

const coordsToString = (coords: any) => `${coords[1].toFixed(3)}:${coords[0].toFixed(3)}`;

export default function Interactions(): JSX.Element {
  const [msg, setMsg] = React.useState("");
  const [feature] = React.useState(new Feature({ geometry: new Point(fromLonLat(coords)) }));
  return (
    <React.Fragment>
      <RMap
        height="90vh"
        className="example-map"
        initial={{ center: fromLonLat(coords), zoom: 11 }}
      >
        {/*<ROSM />*/}
        <RLayerWMTS
          url="https://wxs.ign.fr/essentiels/geoportail/wmts?SERVICE=WMTS&REQUEST=GetCapabilities"
          layer="GEOGRAPHICALGRIDSYSTEMS.PLANIGNV2" />

        <RLayerVector>
          <RStyle.RStyle>
            <RStyle.RIcon src={pin} />
          </RStyle.RStyle>
          <RFeature feature={feature}/>
        </RLayerVector>

        <RInteraction.RTranslate
          onTranslating={React.useCallback((e: any) => {
            const f = e.features.item(0);
            const coords = toLonLat((f.getGeometry() as Point).getFirstCoordinate());
            setMsg(`You placed the pin at ${coordsToString(coords)}`);
          }, [])}
        />
      </RMap>
      {/*<div*/}
      {/*  className="mx-0 mt-0 mb-3 p-1 w-100 jumbotron shadow shadow"*/}
      {/*  dangerouslySetInnerHTML={{ __html: msg }}*/}
      {/*/>*/}
    </React.Fragment>
  );
}
```
This is based loosely on your "Move & Select" example. I have intentionally commented out the div that uses the message which is being updated while moving the pin to demonstrate how **nothing** effectively changes, but the map is still fully reloaded. If you switch out the WMTS layer with ROSM, the problem disappears. Equivalently, if you manually remove the content of the `RLayerWMTS.refresh` method (as mentioned, I'm automating this with `patch-package`), the problem disappears. I don't see any way to work around this, except with monkey-patching the code with `patch-package`.

**Comment by Irfy** [comment]
Now works as intended, thanks for the fix!
