### ISSUE TITLE
Removing features from ol map on RLayerVector component unmount

### ISSUE THREAD

**Issue by Adrien-Atmosphere** [mmomtchev/rlayers#15]
Hi,

When unmounting a RLayerVector (the layer is removed from the app on user action), the features of the layer stay visible on the map. Is it done on purpose ? Should not RLayerVector implement a componentWIllUnmount function where this.source.clear() is called ?

Thanks for your answer !

**Comment by Adrien-Atmosphere** [comment]
Hi

Thanks for fixing this.

I tried the same sandbox with rlayers v1.1.0,  but I'm getting the following error: 

ModuleNotFoundError
Could not find module in path: 'rlayers' relative to '/src/App.js'

See sandbox: https://codesandbox.io/s/zen-zhukovsky-pgfdd

Cheers

**Comment by mmomtchev** [comment]
`rlayers@1.1.0` will be a short-lived version, there was a problem with the build that slipped through
thanks for reporting this

1.1.1 is out
