### ISSUE TITLE
How to get geometry from Interaction draw

### ISSUE THREAD

**Issue by tarmooo** [mmomtchev/rlayers#152]
After following this interaction example: https://mmomtchev.github.io/rlayers/#/draw
i could not get back geometry of the shape that i draw - coordinates, type etc.
Vector onChange method does not give me that or am i wrong?

Anyone know how it is possible?

**Comment by mmomtchev** [comment]
You either have to query all the features from the drawing layer using `source.forEachFeature` or to use the `onDrawEnd` handler of the `RDraw` interaction.

**Comment by tarmooo** [comment]
> You either have to query all the features from the drawing layer using `source.forEachFeature` or to use the `onDrawEnd` handler of the `RDraw` interaction.

Got ya, figured onDrawEnd aswell, thank you! Another thing is to convert coordinates from getCoordinates() to 'EPSG:4326' any clue how transform them? all one by one?

**Comment by mmomtchev** [comment]
There is an example here: https://mmomtchev.github.io/rlayers/#/controls

**Comment by tarmooo** [comment]
What about modifyend event from interaction.modify @mmomtchev ? How to get new coordinates after edit is the question actually.
