### ISSUE TITLE
Draw a route of 10 points on the way

### ISSUE THREAD

**Issue by kibarik** [mmomtchev/rlayers#16]
An excellent library with excellent documentation!
The only thing missing is an example of how to build a route between N points. As a logistician, I want to build a route for the day that passes through 10 points. I could not find the implementation of this functionality in the examples. Can anyone help?

**Comment by mmomtchev** [comment]
Do you have the coordinates of those points or do you need a navigation routine?
Open source navigation is still somewhat immature, it is a very complex field with lots of quirks and a few large proprietary players
If you already have the points, you simply need to include a feature with them

**Comment by kibarik** [comment]
I think to simplify it, you can take an array of 10 prepared points and show an example of drawing a route between these 10 points. Not the construction, but the rendering of the prepared route. Here is an examples of implementation on pure OpenLayers. I would like to understand how to implement this through "RLayers"

Example:
https://github.com/kolosov-sergey/webgl_blog/tree/master/ol/Route

Article (in Russian)
https://devburn.ru/2016/06/26/%D0%BF%D0%BE%D1%81%D1%82%D1%80%D0%BE%D0%B5%D0%BD%D0%B8%D0%B5-%D0%BC%D0%B0%D1%80%D1%88%D1%80%D1%83%D1%82%D0%B0/

Full example from arcgis (build a route from A to B). 
https://developers.arcgis.com/openlayers/route-and-directions/find-a-route-and-directions/

**Comment by kibarik** [comment]
"If you already have the points, you simply need to include a feature with them"
- Can you clarify what you mean

**Comment by kibarik** [comment]
There is a ready-made example on pure "OpenLayers" based on OSRAM-project. Is there any way to create an example of integration with their API via RLayers?

DEMO with openlayers:
https://map.project-osrm.org/ 

Next month we will try to integrate RLayers with this service. If there are any questions in the process, I will ask them in this thread. If everything works out in the end, you can add another demo to your documentation

**Comment by kibarik** [comment]
The main question is how to draw a straight line through Players using the code now. I didn't find an example in your documentation. Just a straight line between two points

**Comment by mmomtchev** [comment]
@kibarik thank you for this excellent example, even if my Russian is somewhat rusty :smile:
