### ISSUE TITLE
Change RCircle radius when zoom changes

### ISSUE THREAD

**Issue by brucelane** [mmomtchev/rlayers#166]
Hi, thank you for this awesome and useful project!

I'm creating a RCircle with a radius corresponding to the distance in meters.
When I zoom, the circle stays the same size...

How can I approach this? 
Should I retrieve the zoom level and adapt the radius by code or is there a better way?

**Comment by mmomtchev** [comment]
An `<RCircle>` element is an icon, not a map feature. You need to create a map feature with a circle geometry expressed in projection units. Remember that depending on your projection, a circle on the ground might not be a circle when projected on the map.

Look at this example which simply uses meters as a circle radius in Web Mercator to create a circle on the map which will in fact be a somewhat distorted ellipse on the ground:
https://github.com/mmomtchev/xc-db/blob/main/src/front/MapRoute.tsx
