### ISSUE TITLE
Typescript error cannot use Component as a JSX Component

### ISSUE THREAD

**Issue by hoanganh57** [mmomtchev/rlayers#169]
![image](https://github.com/mmomtchev/rlayers/assets/73334269/dbf32126-d08d-48b4-ab41-13eaf2cdd124)
When i use component like picture, this error in VSCode but code run without error. When i build, same error and cannot build
Update: I found the cause, typescript version 5.1.3 and higher versions build error

**Comment by mmomtchev** [comment]
Fixed by #165, 2.0.0 supports recent TypeScript versions

**Comment by hoanganh57** [comment]
> Fixed by #165, 2.0.0 supports recent TypeScript versions

How long the 2.0 version will be release?

**Comment by mmomtchev** [comment]
There is a release available by installing `rlayers@next`. There hasn't been any problems reported, so it will probably get re-released as 2.0.0.

**Comment by mmomtchev** [comment]
Fixed by #171
