### ISSUE TITLE
How do I configure tileSize?

### ISSUE THREAD

**Issue by mschilde** [mmomtchev/rlayers#173]
I'm building a map using `Rlayers` and `Maptiler` and would like to pass the `tileSize` parameter.

Code in vanilla OL:

```
new TileLayer({
  source: new TileJSON({
    url: `https://api.maptiler.com/maps/${tileStyle}/tiles.json?key=${mapTilerKey}`,
    tileSize: 512
  })
});
```

Code in rlayers:

```
<RLayerVector>
      <RLayerTileJSON
        url={`https://api.maptiler.com/maps/${tileStyle}/tiles.json?key=${mapTilerKey}`}
      />
</RLayerVector>
```

This mainly works, but without supplying a tile size the labels (street and city names) in Maptiler are very small and hard to read.

Is there a way to provide this parameter?

**Comment by mmomtchev** [comment]
No, it is currently absent from the options, I will merge it if you add it, it is a trivial PR
