### ISSUE TITLE
RStadiaLayer is not being exported

### ISSUE THREAD

**Issue by HernanPaez** [mmomtchev/rlayers#197]
Hi there! 
I am trying to use the RStadiaLayer on my Next.js app but the compiler throws this error:

`Module not found: Package path ./layer/RLayerStadia is not exported from package /Users/redacted/redacted/redacted-web/node_modules/rlayers (see exports field in /Users/redacted/redacted/redacted-web/node_modules/rlayers/package.json).
`
It's kinda weird because I'm using the RLayerTile component just fine.

This is the import line:
`import RLayerStadia from "rlayers/layer/RLayerStadia";`

Is there a workaround for this error?

**Comment by mmomtchev** [comment]
Maybe I have missed it, too bad, I will fix it and stay hungry for some more years

**Comment by mmomtchev** [comment]
Until I learn
