### ISSUE TITLE
Cannot get the Simple map example to work

### ISSUE THREAD

**Issue by barthogenes** [mmomtchev/rlayers#2]
Hi, 
I was trying to get the Simple map example to work from https://mmomtchev.github.io/rlayers/#/simple,
but all I get is the following error on build:
![image](https://user-images.githubusercontent.com/20557666/123116347-209c2980-d441-11eb-9526-23f681bdcba8.png)
I made sure to use React version `16.8.0`.
My dependencies from the package.json:
```json
"dependencies": {
    "@testing-library/jest-dom": "^5.11.4",
    "@testing-library/react": "^11.1.0",
    "@testing-library/user-event": "^12.1.10",
    "@types/jest": "^26.0.15",
    "@types/node": "^12.0.0",
    "@types/react": "^16.14.8",
    "@types/react-dom": "^16.9.13",
    "ol": "^6.5.0",
    "react": "^16.8.0",
    "react-dom": "^16.8.0",
    "react-scripts": "4.0.3",
    "rlayers": "^1.0.2",
    "typescript": "^4.1.2",
    "web-vitals": "^1.0.1"
  },
  "devDependencies": {
    "@types/ol": "^6.5.1"
  }
```

Am I doing something wrong?

**Comment by mmomtchev** [comment]
Can you post your `tsconfig.json`

**Comment by barthogenes** [comment]
Here it is:
```json
{
  "compilerOptions": {
    "target": "es5",
    "lib": [
      "dom",
      "dom.iterable",
      "esnext"
    ],
    "allowJs": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "noFallthroughCasesInSwitch": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "react-jsx"
  },
  "include": [
    "src"
  ]
}
```

**Comment by mmomtchev** [comment]
@barthogenes, you can temporally set `"strict": false`, I will soon release a new version the compiles when strict mode is enabled

**Comment by barthogenes** [comment]
Turning off `strict` mode fixed it indeed :)

> @barthogenes, you can temporally set `"strict": false`, I will soon release a new version the compiles when strict mode is enabled

Thanks that would be great!
Closing this ticket then.
