### ISSUE TITLE
Calling an event only once

### ISSUE THREAD

**Issue by andreighh** [mmomtchev/rlayers#235]
Hello,

Is it possible to call an event only once for the map (`map.once("rendercomplete"...`)? I'm trying to use `onRenderComplete` but I want it to run only once. Thank you.

**Comment by mmomtchev** [comment]
You should do it the *React* way - by adding state to your component and setting that handler based on the state.

This is the React way of doing things.

**Comment by mmomtchev** [comment]
First:

```js
const [called, setCalled] = React.useState(false);
```

Then:

`<.... onRenderComplete={called ? undefined : yourHandler} ... >`

**Comment by andreighh** [comment]
I was thinking it's not the right way, but I see I'm wrong, thank you for the help and your time.
