### ISSUE TITLE
RLayerTileWMS refresh unexpectly

### ISSUE THREAD

**Issue by boborua** [mmomtchev/rlayers#248]
When we having a parent component holding some state and then change the state, for example below:

```React
const App = () => {
  cont [count, setCount] = React.useState(0);
  return <RMap onChange={() => setCount(s => s + 1)}>
    <RLayerTile>
      <RLayerTileWMS url={xxx} />
    </RLayerTile />
  </RMap>
}
```
`RLayerTileWMS` will refresh unexpectly, cause the base component `RlayersBase` in `src/REvent.tsx` claims the `componentDidUpdate` and just compared the props reference.

The reason is the same as issue #144

Currently i've make a work around and works properly which overrides `RLayerTileWMS` component as follow:
```React
class CustomRLayerTileWMS extends RLayerTileWMS {
  componentDidUpdate(
    prevProps: Readonly<RLayerTileWMSProps>,
    prev: Readonly<unknown>,
    snap: unknown
  ): void {
    if (super.propsDiff(prevProps)) {
      super.componentDidUpdate(prevProps, prev, snap);
    }
  }
}
```

**Comment by mmomtchev** [comment]
I am not very sure that this is a good idea, `propsDiff` is mostly a debugging aid.

This is an artificial edge case. Normally, you should have used `useCallback` on the map to prevent excessive refreshing. Maybe there are some optimizations possible, but it would be very bug prone and I don't think it will help a lot for any real-world use case. Also, you are not supposed to nest layers.

**Comment by mmomtchev** [comment]
Just imagine, in your case, what would happen if you had another nested level inside - for example with a feature - and its property did change depending on the map property. You would have blocked the propagation down the chain.

**Comment by boborua** [comment]
Thanks for your time.

Considering this case
```React
const App = () => {
  cont [count, setCount] = React.useState(0);
  return <RMap onChange={() => setCount(s => s + 1)}>
    <RLayerTile>
      <RLayerTileWMS url="https://example.com/wms" />
    </RLayerTile />
  </RMap>
}
```
After going throught some source code, i know that
 `RLayerTileWMS` extends `RLayerBase` which eventually has base class `PureComponent`. When `state` in wrapper compoent(App) changes, `RlayerTileWMS` should not be renderred because all i'ts props (only url in this case) are not changing. But the `componentDidUpdate` did called. It makes me confusing... (Maybe the context is changing)

**Comment by mmomtchev** [comment]
The context probably changes, but you are not supposed to be nesting layers at all. I don't want to optimize this case, as it will be very error-prone and it is an artificial edge case that forces an update of `RMap` component. This should have been a constant function obtained by `useCallback` - otherwise it will surely kill performance.

**Comment by boborua** [comment]
Sorry for my copy&past mistake, in my minimum case, `RLayerTileWMS` is not nested.
```
const App = () => {
  cont [count, setCount] = React.useState(0);
  return <RMap onChange={() => setCount(s => s + 1)}>
      <RLayerTileWMS url="https://example.com/wms" />
  </RMap>
}
```

**Comment by mmomtchev** [comment]
Ok, now it is correct, but it is still an artificial case.

**Comment by mmomtchev** [comment]
If you submit a PR that does not touch the base classes, but only `RLayerTileWMS`, I will consider it. Do not use `propsDiff`, it is a debugging aid.

**Comment by mmomtchev** [comment]
Yes, rerendering a layer would replace the context object. If your problem is only with the `RLayerTileWMS`, I prefer that you modify only this component. Currently, it will recreate the source, because the settings cannot be changed. This can probably be memoized.

Directly memoizing the context object could save rerenders, but it is a dangerous change that would have to be very thoroughly tested.
