### ISSUE TITLE
Source mapping points to incorrect path

### ISSUE THREAD

**Issue by pajablons** [mmomtchev/rlayers#25]
Fresh project / install via npm.  rlayers@1.2.1.  

Source maps for most (if not all) files, are pointing to $PROJ/node_modules/src/..., rather than $PROJ/node_modules/rlayers/src/...

Example: 
`Failed to parse source map from '/DATA/workspace/ol_proj/frontend/node_modules/src/style/index.ts' file: Error: ENOENT: no such file or directory, open '/DATA/workspace/oj_proj/frontend/node_modules/src/style/index.ts'
 @ ./node_modules/rlayers/index.js 224:30-48
 @ ./src/App.tsx 6:0-37 12:32-36 18:37-41
 @ ./src/index.tsx 7:0-24 11:33-36
`

No real functional issue, but incredibly annoying since it floods my console.

**Comment by mmomtchev** [comment]
Fastest way around this is to simply delete `*.map` from `node_modules/rlayers`, you won't need them if you are not debugging rlayers
