### ISSUE TITLE
onTranslateEnd

### ISSUE THREAD

**Issue by GreenJimmy** [mmomtchev/rlayers#27]
I can't get onTranslateEnd to fire when filtering different layers, am I just being dumb?
If I remove the filter it fires as it should - I just don't need every layer to be moveable

`<RInteraction.RTranslate
    filter={(feature) => {
        return feature.getProperties().type === 'moveable';
    }}
    onTranslateEnd={(e) => {
        console.log(e);
    }}
/>`

**Comment by mmomtchev** [comment]
When you pass a function in this manner, without `useCallback`, the function will get recreated at each update - this is what triggers the bug.
If you memoize the function, you will work around the bug.

**Comment by GreenJimmy** [comment]
Yes sorry, I had useCallback there previously and it worked ... until I added the filter. I switched to trying with returning only the layers I want moveable AND with useCallback and it is still not firing. 

`<RInteraction.RTranslate
              layers={(layer) => layer.getProperties().type === 'moveable'}
              onTranslateEnd={useCallback((e) => {
                  console.log('event', e);
              }, [])}
          />`

**Comment by GreenJimmy** [comment]
Thought I had it after trying out alpha.1 - but no, this still does not work:
`<RInteraction.RTranslate
                layers={(layer) => layer.getProperties().type === 'moveable'}
                onTranslateEnd={useCallback((e) => {
                    console.log('event', e);
                }, [])}
            />`

**Comment by GreenJimmy** [comment]
Using your own example for Interaction and Translate I can get onTranslateEnd to fire once and then it stops firing:
`<RInteraction.RTranslate
                    filter={(feature) => feature.get('name') === "Place d'Italie"}
                    onTranslateEnd={React.useCallback((e) => {
                        const f = e.features.item(0);
                        const coords = toLonLat(f.getGeometry().getFirstCoordinate());
                        setMsg(
                            `You placed <strong>${f.get('name')}</strong> at ${coordsToString(
                                coords,
                            )}`,
                        );
                    }, [])}
                />`

**Comment by GreenJimmy** [comment]
My bad, you were referring to adding useCallback to the filter attr 🤦‍♂️
