### ISSUE TITLE
Inverted zIndex

### ISSUE THREAD

**Issue by devnesi** [mmomtchev/rlayers#321]
I am using RLayerVectorTile, passing the zIndex in the properties, but the rendering seems inverted, I believe. For example, if I have two layers, the first with index 1 and the second with index 2, and with two overlapping geometries, the one with index 2 should be on top of the one with index 1, but that's not happening. However, the click events are working as expected, respecting the higher index. Can you help me?

**Comment by nodgear** [comment]
Let me exemplify: 
 - Render 6 VectorLayerTile's, with unique zIndexes for each one (from 1 to 6)
   - Click on an area where 2 tiles overlaps
     - The click event will be fired on the layer with highest zIndex (correct behavior)
- The layers with higher zIndex are rendered bellow the ones with smaller zIndex (inverse of what one might expect)
  - The order in which the VectorLayerTile is in the DOM does not change this fact if zIndex is set
    - If zIndex is not set, the order in DOM affects the render order but not the priority when interacting with the overlapping layers (the one being rendered behind will be the one receiving the event)

**Comment by devnesi** [comment]
I was able to understand the behavior: actually, when I click on overlapping geometries, an event will be triggered for each geometry, and I was only handling the last one.

Thanks to #265, I was able to notice.
