### ISSUE TITLE
Popups only appear after hot reload

### ISSUE THREAD

**Issue by abkfenris** [mmomtchev/rlayers#35]
I'm attempting to upgrade from 1.1.1 to 1.3.1 and hitting a rather weird issue. 

Each feature should have a linked popup. The popups don't display on hover after an initial load of the page. However if I change the code of the popup and it hot reloads, then the popups display. They again do not display after a full reload of the page.

I'm not exactly sure where to start debugging this one. I tried updating to 1.2.1 instead, but then hit onClick not firing on features which appeared to be fixed in 84bfd72.

https://user-images.githubusercontent.com/1296209/156207591-b7d1aa6c-9d88-4ed6-b6cb-f09763072fbb.mov

Here is the branch of my project that I'm working on that's having this issue: https://github.com/gulfofmaine/Neracoos-1-Buoy-App/pull/1766/

**Comment by mmomtchev** [comment]
Can you extract just that component as a text and post it here, I am unable to run your project

**Comment by abkfenris** [comment]
Each point comes from the `PlatformLayer` component which has a few options for styling. `platform` is a GeoJSON Feature, with a few extra properties that aren't used here.

```tsx
const PlatformLayer = ({ platform, selected, old = false }: PlatformLayerProps) => {
  const navigate = useNavigate()

  let radius: number
  if (selected) {
    radius = window.innerWidth > adjustPxWidth ? 10 : 15
  } else {
    radius = window.innerWidth > adjustPxWidth ? 5 : 10
  }
  const opacity = selected ? "cc" : "7a"

  const url = generatePath(paths.platforms.platform, { id: platform.id })

  const fillColor = old ? "grey" : `#cf5c00${opacity}`
  const strokeColor = old ? "grey" : colors.whatOrange

  return (
    <RLayerVector>
      <RStyle.RStyle>
        <RStyle.RCircle radius={radius}>
          <RStyle.RFill color={fillColor} />
          <RStyle.RStroke color={strokeColor} width={1.5} />
        </RStyle.RCircle>
      </RStyle.RStyle>
      <RFeature
        feature={new GeoJSON({
          dataProjection: "EPSG:4326",
          featureProjection: "EPSG:3857",
        }).readFeature(platform)}
        onClick={React.useCallback(() => {
          navigate(url, { replace: false })
        }, [])}
      >
        <RPopup trigger={"hover"}>
          <Button
            color="dark"
            size="sm"
            onClick={React.useCallback(() => {
              navigate(url, { replace: false })
            }, [])}
          >
            {platform.id}
          </Button>
        </RPopup>
      </RFeature>
    </RLayerVector>
  )
}
```

**Comment by mmomtchev** [comment]
Don't use the `feature` property for this, it is a very special property for when you need to bind the feature to an existing feature

Use `geometry`

**Comment by abkfenris** [comment]
Awesome, thank you. Using `geometry` worked.

So, to make sure I'm understanding this, `feature` requires a stable OpenLayers feature, so because the events can be bound?

When I changed the code and it hot reloaded within the `RPopup`, then it was able to connect to the (somewhat ephemeral) feature that I generated in `RFeature`, but on a fresh load it is not able to connect the events?

For anyone else ending up here, this is what I changed `RFeature` into.

```tsx
<RFeature
        geometry={React.useMemo(() => {
          const feature = new GeoJSON({
            dataProjection: "EPSG:4326",
            featureProjection: "EPSG:3857",
          }).readFeature(platform)
          return feature.getGeometry()
        }, [platform])}
        onClick={React.useCallback(() => {
          navigate(url, { replace: false })
        }, [])}
      >
```

**Comment by mmomtchev** [comment]
It used to require a stable feature, now some form of updating is supported, but as this completely bypasses React - the feature being an opaque type for React - not everything works
This property is meant mostly for interfacing with non-React OpenLayers code, I will probably underline this in the doc

**Comment by abkfenris** [comment]
Thank you, that makes sense why it wasn't working as I expected.
