### ISSUE TITLE
rlayers draw and getFeatureInfo onClick

### ISSUE THREAD

**Issue by fogracvxy** [mmomtchev/rlayers#38]
Is there inbuilt ways to use rlayers to draw on map and already created component to get getFeatureInfo from clicked layer. If no I would like to see it in new versions :)

Love rlayers amazing work!

**Comment by fogracvxy** [comment]
> I don't understand, you want to draw on a map created by other means, not rlayers?

I want to draw on map created with rlayers <RMap>

**Comment by mmomtchev** [comment]
Make an `onClick` handler, get the coordinates (there is an example) and your WMS source will be in `this.source`

**Comment by fogracvxy** [comment]
How would you do `onClick` handler to get feature info from WMS `<RLayerTileWMS> `  and show it table like :)

**Comment by mmomtchev** [comment]
Check the OpenLayers examples for `getFeatureInfo` : https://openlayers.org/en/latest/examples/getfeatureinfo-tile.html

If you define an `onClick` handler on a `<RLayerTileWMS>`, the WMS source will be available in `this.source`

Check the rlayers examples for how to get the coordinates

**Comment by fogracvxy** [comment]
Is is not letting me define onClick on  <RLayerTileWMS> I mean tried console logging string out and it doesn't print anything if clicked

**Comment by mmomtchev** [comment]
I am sorry, the `onClick` should be on the map (TypeScript wouldn't have let you define an `onClick` on `RLayerTileWMS` in the first place). Only vector layers have an `onClick` which calls you with the clicked feature and the `RMap` itself which calls you with the map coordinates of the click. A raster layer can't have a click handler. The `Add & Delete` example gets the coordinates from the click according to the map projection. Then you must define a reference on your `RLayerTileWMS`:
```tsx
const ref = React.useRef<RLayerTileWMS>();
return (
  <RLayerTileWMS
                  ref={ref}
                  key={item.value}
                  visible={item.visible}
                  opacity={item.opacity}
                  url={url}
                  params={{
                    LAYERS: item.layer_name,
                    FORMAT: "image/png",
                    serverType: "geoserver",
                  }}
  />
);
````
and finally access the source to call `getFeatureInfo`: 
```tsx
if (ref.current) ref.current.source.getFeatureInfo()
```

**Comment by fogracvxy** [comment]
Am i doing it right I mean I don't know how am I supposed to get resolution to pass and getFeatureInfoUrl()
```
<RMap
          width={"100%"}
          height={"93.2vh"}
          className="example-map"
          initial={useMemo(() => ({ center: center, zoom: 10 }), [])}
          onPointerMove={useCallback((e) => {
            //test za dohvat koordinata na pomaku misa
            const point = e.map.getCoordinateFromPixel(e.pixel);
            const lonlat = toLonLat(point);
            setMoveLoc(lonlat);
          }, [])}
          onClick={useCallback((e) => {
            const coords = e.map.getCoordinateFromPixel(e.pixel);
            const resolution = e.view.getResolution();
            const lonlat = toLonLat(coords);
            if (geoVectorLayer.current) {
              console.log(
                geoVectorLayer.current.source.getFeatureInfoUrl(
                  coords,
                  resolution,
                  "EPSG:3857",
                  { INFO_FORMAT: "text/html" }
                )
              );
            }
            setLoc(lonlat);
          }, [])}
        >

**Comment by fogracvxy** [comment]
Managed to get url with this technique
`import View from "ol/View";`
and then created new View
`const view = new View({ center: center, zoom: 10 });`


```
<RMap
          width={"100%"}
          height={"93.2vh"}
          className="example-map"
          initial={useMemo(() => ({ center: center, zoom: 10 }), [])}
          onPointerMove={useCallback((e) => {
            //test za dohvat koordinata na pomaku misa
            const point = e.map.getCoordinateFromPixel(e.pixel);
            const lonlat = toLonLat(point);
            setMoveLoc(lonlat);
          }, [])}
          onClick={useCallback((e) => {
            const coords = e.map.getCoordinateFromPixel(e.pixel);
            const resolution = view.getResolution();
            const lonlat = toLonLat(coords);
            if (geoVectorLayer.current) {
              console.log(
                geoVectorLayer.current.source.getFeatureInfoUrl(
                  coords,
                  resolution,
                  "EPSG:3857",
                  { INFO_FORMAT: "text/html" }
                )
              );
            }
            setLoc(lonlat);
          }, [])}
        >
        ```
Do you recommend any other way?

**Comment by mmomtchev** [comment]
The pure `rlayers` method is to set an external `RView` as in the external state example. `zoom` and `resolution` are different representations of the same parameter. `getResolutionForZoom()` can transform it.
Or, you can call `this.ol.getView()` in `RMap` handlers.
If you create a new `View` it won't be linked to your existing map.

**Comment by fogracvxy** [comment]
Will test it out in the morning at first I thought everything is okey with resolution but then wherever I click i get layer name from the same layer could it be that it referenced last loaded layer and it now only uses its name i am mapping out layers from an array could it be a problem

**Comment by fogracvxy** [comment]
Is there way to get all the values that I ref here 
```javascript
       
 {arrayLayera.map((item) => {
            return (
              <RLayerTileWMS
                key={item.value}
                ref={geoVectorLayer}
                visible={item.visible}
                opacity={item.opacity}
                url={url}
                params={{
                  LAYERS: item.layer_name,
                  FORMAT: "image/png",
                  serverType: "geoserver",
                }}
              />
            );
          })}```

It only give me last value with useRef()
```javascript
 if (geoVectorLayer.current) {
              console.log(
                geoVectorLayer.current.source.getFeatureInfoUrl(
                  coords,
                  resolution,
                  "EPSG:3857",
                  { INFO_FORMAT: "text/html" }
                )
              );
            }
            setLoc(lonlat);
          }, [])}
```
Is there way that I can access them with ref but not the only last mapped item

**Comment by mmomtchev** [comment]
https://mattclaffey.medium.com/adding-react-refs-to-an-array-of-items-96e9a12ab40c
