### ISSUE TITLE
Custom loader for RLayerTile

### ISSUE THREAD

**Issue by Macklawe** [mmomtchev/rlayers#39]
Hi, I try to load tile from a server, and i recieve error, because my request is without correct token. How can i provide axios or token to request?
![tile](https://user-images.githubusercontent.com/13092541/160630498-7f2e6d16-d5d1-406f-bceb-d8074b2aa25a.png)
![error](https://user-images.githubusercontent.com/13092541/160630514-61621d58-72e2-49c6-ab41-f0b2536c1772.png)

**Comment by mmomtchev** [comment]
What form does your token have? URL parameter or HTTP header?

**Comment by Macklawe** [comment]
As http header

**Comment by mmomtchev** [comment]
Check https://mmomtchev.github.io/rlayers/#/addon for how to extend rlayers
Create your own layer class extending from `RLayerTile` and overload only this function:

```ts
class AuthLayerTyle extends RLayerTile {
  createSource(): void {
      this.source = new XYZ({
          url: this.props.url,
          projection: this.props.projection,
          tileGrid: this.props.tileGrid,
          tileLoadFunction: <your_tile_load_function>
      });
      this.eventSources = [this.ol, this.source];
}
```

Also check this stackoverflow answer which, even if it is a bit old, still works: https://stackoverflow.com/questions/49095151/how-to-add-a-http-header-to-openlayers4-requests

These days you can use the `fetch` API which is better.

**Comment by Macklawe** [comment]
Thanks a lot. It works
