### ISSUE TITLE
Cannot get the map to work

### ISSUE THREAD

**Issue by FabAlchemy** [mmomtchev/rlayers#4]
Hi,

The Typescript compilers complains when running the _Simple map_ example :

```
'RMap' cannot be used as a JSX component.
  Its instance type 'RMap' is not a valid JSX element.
    Types of property 'componentDidUpdate' are incompatible.
      Type '(prevProps: RMapProps, prev: null, snap: unknown) => void' is not assignable to type '(prevProps: Readonly<any>, prevState: Readonly<{}>, snapshot?: any) => void'.
        Types of parameters 'prev' and 'prevState' are incompatible.
          Type 'Readonly<{}>' is not assignable to type 'null'.
```

I'm using React `17.0.1` and the `strict` Typescript mode is enabled (I saw the similar #2 issue).
Am I missing something?

**Comment by mmomtchev** [comment]
Does the issue go away if you remove `strict`?

**Comment by mmomtchev** [comment]
@FabAlchemy, try 1.0.4, it should be compatible with React 17 in strict mode

**Comment by FabAlchemy** [comment]
The errors disappeared, thank you for your quick help!
