### ISSUE TITLE
WFS Feature Layer Popup with attributes on click

### ISSUE THREAD

**Issue by gmonk** [mmomtchev/rlayers#45]
How would I go about producing a pop from a wfs layer ?   I am able to successfully pull the layer in and log the location attribute to the console with the code below.  This pulls from a  local pg_featureserv  instance displaying cctv locations as  a point. All the examples of popups seem to create a popup that is wrapped in a feature.  But Im not sure how to go about this if I am already pulling the features into the layer.  Sorry for the noob questions but I mostly work on the backend and I am trying to learn more frontend.

Thanks

 <RLayerVector
            properties={{ label: "CCTV" }}
            zIndex={1}
            format={new GeoJSON({ featureProjection: "EPSG:4326" })}
            url="http://localhost:9000/collections/public.cctv/items.json?limit=500"
            onClick={React.useCallback(
              (e) => console.log(e.target.get("location")),
              []
            )}
          ></RLayerVector>

**Comment by mmomtchev** [comment]
Create a single additional feature with a geometry in a React state to wrap your popup
```js
const [ geom, setGeom ] = React.useState();
```
```jsx
<RFeature geometry={geom}>
  <RPopup />
</RFeature>
```
Use an `onPointerEnter` event on the layer with the features and use `setGeom` on the popup holding feature with the feature location to move your popup

You can also define `onPointerLeave` if you want to hide the popup when moving the mouse away
