### ISSUE TITLE
RLayerVectorTile

### ISSUE THREAD

**Issue by gmonk** [mmomtchev/rlayers#48]
Does the RLayerVectorTile support popup ?  I have two layers one layers is a vector layer which I am now able to provide a popup for each point.  I also have a VectorTileLayer which contains multiple polygons from local pg_tileserver  but when I try to add the pop to provide details of each polygon on click i get an error saying the "RFeature must be part of a vector layer" Which I am assuming to mean it is not supported in VectortileLayers unless i am missing somthing.

Thank You

**Comment by mmomtchev** [comment]
Duplicate of https://github.com/mmomtchev/rlayers/issues/45

You must have a static feature for a popup.
