### ISSUE TITLE
Example visualization. Geolocation

### ISSUE THREAD

**Issue by santiagotsp** [mmomtchev/rlayers#5]
Cannot use namespace 'GeometryType' as a type.  TS2709

    62 | 
    63 |                     <RInteraction.RDraw
  > 64 |                         type={"Polygon" as GeometryType}
       |                                            ^
    65 |                         condition={shiftKeyOnly}
    66 |                         freehandCondition={altShiftKeysOnly}
    67 |                     />

**Comment by mmomtchev** [comment]
https://github.com/openlayers/openlayers/issues/12497

**Comment by santiagotsp** [comment]
This is my tsconfig.json before running the app and Geolocation.tsx doesn´t show any errors.
`{
  "compilerOptions": {
    "target": "es5",
    "lib": [
      "dom",
      "dom.iterable",
      "esnext"
    ],
    "allowJs": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "strict": false,
    "forceConsistentCasingInFileNames": true,
    "noFallthroughCasesInSwitch": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "react-jsx",
    "baseUrl": "./",
    "paths": {
      "ol": [
        "node_modules/@types/ol"
      ],
      "ol/*": [
        "node_modules/@types/ol/*"
      ]
    },
  },
  "include": [
    "src"
  ]
}`

After running the app the tsconfig.json changed to (deletes paths attribute):
`{
  "compilerOptions": {
    "target": "es5",
    "lib": [
      "dom",
      "dom.iterable",
      "esnext"
    ],
    "allowJs": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "strict": false,
    "forceConsistentCasingInFileNames": true,
    "noFallthroughCasesInSwitch": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "react-jsx",
    "baseUrl": "./"
  },
  "include": [
    "src"
  ]
}
`

The Geolocatio.tsx file show this errors:
![error_rlayers](https://user-images.githubusercontent.com/42518145/125808449-1a170284-2d93-4cab-bf33-f32629463db0.png)

**Comment by mmomtchev** [comment]
Yes, the new OpenLayers 6.6.0 native Typescript types are not compatible, you have to keep the `paths` for now
An eventual new *rlayers 1.1* version will support the new Typescript types, but it won't be compatible with OpenLayers < 6.6.0
I am still waiting for the typings to stabilize - there was a new 6.6.1 release a few hours ago - and I will publish *rlayers 1.1*
For now the only way to use OpenLayers 6.6.0 with Typescript is to add the `paths` attribute
