### ISSUE TITLE
How to use another tile library like Thunderforest

### ISSUE THREAD

**Issue by markfilius** [mmomtchev/rlayers#72]
Hi, 
Thanks for rlayers - an extremely promising solution!

I want to use rlayers with Thunderforest tiles. It seems (by looking at the types) that the correct syntax should be:
`        <ROSM source={
            'https://tile.thunderforest.com/outdoors/{z}/{x}/{y}.png?apikey=<key>'
          }
        />
`

But unfortunately that is not correct. Can you tell me what the correct manner is to use another tile library?

Thanks!

**Comment by ashishnex007** [comment]
> The OpenLayers implementation does not allow customization of the OSM layer - there are copyright issues and it must be included the way it is. If you want to use another XYZ source, you must use `RLayerTile`.

That means we can use other tile providers for custom tiles as long as it in RLayerTile right? Btw, I want a satellite map, I can achieve it by using the RlayerTile with URL right?
