### ISSUE TITLE
Use Rlayers with QGIS Server

### ISSUE THREAD

**Issue by dmestudent** [mmomtchev/rlayers#9]
Hello, 

first of: Thank you for this project. I am currently looking through the docs and the examples and it is brilliant. 

I have a question regarding if it is already support or how you would go about using WMS layers served by a qgis server? I am currently writing my own react web app to consume a qgis server. 

Best regards,
dmeStudent

**Comment by mmomtchev** [comment]
There is no WMS support at the moment - but it is relatively easy to implement it from the WMTS layer

**Comment by dmestudent** [comment]
Okay thank you for the quick response. I think I will have to build a temp workaround for my case then until it is implemented. I would love to do it myself but I have no knowledge about how I can extend a library that is written in typescript since I have no typescript experience 😅

**Comment by abkfenris** [comment]
I've got a `TileWMS` layer working, but only supporting the WMS options that I need at this point. `TileLayer` and `TileWMS` can be quickly swapped for `ImageLayer` and `ImageWMS` if your source doesn't support tiled WMS requests.

```typescript
import React from "react"
import { RContextType, RLayer, RLayerProps } from "rlayers"
import { toast } from "react-toastify"

import TileLayer from "ol/layer/Tile"
import TileWMS from "ol/source/TileWMS"

export interface RTileWMSLayerProps extends RLayerProps {
  // attributions
  // attributionsCollapsible
  // cacheSize
  // crossOrgin
  // imageSmoothing
  params: { [key: string]: any }
  // gutter
  // hidip
  // projection
  // reprojectionErrorThreshold
  // tileClass
  // tileGrid
  // serverType
  // tileLoadFunction
  url?: string
  //   urls?: [string]
  // wrapX
  // transition
  // zDirection
}

export class RTileWMSLayer extends RLayer<RTileWMSLayerProps> {
  ol: TileLayer
  source: TileWMS

  constructor(
    props: Readonly<RTileWMSLayerProps>,
    context: React.Context<RContextType>
  ) {
    super(props, context)
    this.createSource()
    this.ol = new TileLayer({ source: this.source })
    this.eventSources = [this.ol, this.source]
  }

  createSource(): void {
    const { params, url } = this.props
    const options = { params, url }

    console.log(options)

    this.source = new TileWMS(options)
    this.eventSources = [this.ol, this.source]
  }

  refresh(prevProps?: RTileWMSLayerProps): void {
    super.refresh(prevProps)
    this.createSource()
  }
}
```

**Comment by mmomtchev** [comment]
You can submit a PR if you wish

**Comment by mmomtchev** [comment]
rlayers 1.1 has basic TileWMS support
